# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu_login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "51",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjUyMSwiaWF0IjoxNjA2Mjk0NTIxfQ.8P6Qaxs4TcQaHK2DBwUCykHOuNzc8RE6-QJZpG-4c5_TmjNUruXJTRyaZR4wZVSdtnE7sYCUvf2KZStTKq9qSw",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                }
            )
            .with_data(
                {"phone": "13161996611", "password": "zll122644.", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("https://mubu.com/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjU1MiwiaWF0IjoxNjA2Mjk0NTUyfQ.HmRh9JwKDXusqp5vS_tKYN3wgg61h7ycQPOjATkqfSK8rNM6ZtKkK3ja79U_LaUOb1iUiRqHHd8zXUFRwSP8mQ",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/photo/0246100e-c0a9-4d58-a866-64e5cece85a2.jpg@50w_50h")
            .get(
                "https://mubu.com/photo/0246100e-c0a9-4d58-a866-64e5cece85a2.jpg@50w_50h"
            )
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "image",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjU1MiwiaWF0IjoxNjA2Mjk0NTUyfQ.HmRh9JwKDXusqp5vS_tKYN3wgg61h7ycQPOjATkqfSK8rNM6ZtKkK3ja79U_LaUOb1iUiRqHHd8zXUFRwSP8mQ",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("https://mubu.com/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjU1MiwiaWF0IjoxNjA2Mjk0NTUyfQ.HmRh9JwKDXusqp5vS_tKYN3wgg61h7ycQPOjATkqfSK8rNM6ZtKkK3ja79U_LaUOb1iUiRqHHd8zXUFRwSP8mQ",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("https://mubu.com/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjU1MiwiaWF0IjoxNjA2Mjk0NTUyfQ.HmRh9JwKDXusqp5vS_tKYN3wgg61h7ycQPOjATkqfSK8rNM6ZtKkK3ja79U_LaUOb1iUiRqHHd8zXUFRwSP8mQ",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("https://mubu.com/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1166637491.1605089432",
                    "data_unique_id": "4720bdd1-8376-469f-aa92-82892dd071c4",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1625043998.1606286401",
                    "s_v_web_id": "khx1jvey_WSxpxxif_9s8d_4NvD_9otJ_oRWZOPVMrYkZ",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1605089577,1606286573",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "csrf_token": "7d7402e5-93ae-4b2a-90ca-6d7cb4afe4be",
                    "data-unique-id": "a590eea0-2efb-11eb-a44a-19091463577f",
                    "SESSION": "99b9d8bc-1c75-43d5-9ba9-a8b71977cddf",
                    "reg_prepareId": "175fe9ca099-175fe9ca034-4b48-b906-009786259b23",
                    "reg_focusId": "681a9cee-b639-4b48-b906-175fe9ca5d6",
                    "user_persistence": "3a6a9eb1-cf7c-451a-92bb-7fb91e4a74d4",
                    "SLARDAR_WEB_ID": "54acc6af-68b3-45e5-b14b-3a63911d608c",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1606294528",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTgxOTE0OCIsImV4cCI6MTYwODg4NjU1MiwiaWF0IjoxNjA2Mjk0NTUyfQ.HmRh9JwKDXusqp5vS_tKYN3wgg61h7ycQPOjATkqfSK8rNM6ZtKkK3ja79U_LaUOb1iUiRqHHd8zXUFRwSP8mQ",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
